name: Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 5 minutes

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Hugging Face Space
        run: curl -f https://huggingface.co/spaces/yomayank/carrer_agent || exit 0
